<?php
declare(strict_types=1);
// Page: ?page=ussd_flows — included by index.php inside its try/catch, after the sign-in, CSRF and $page checks.

    require_perm('manage_ussd_menus'); flow_tables();
    $flowUrl=fn(string $k,string $x='')=>'?page=ussd_flows&flow='.urlencode($k).$x;
    if ($_SERVER['REQUEST_METHOD']==='POST') {
        $do=(string)($_POST['do']??''); $fk=trim((string)($_POST['flow_key']??''));
        if ($do==='new_flow') { $k=save_flow($_POST); flash('success','Flow created. Add or change its steps below.'); redirect($flowUrl($k)); }
        if ($do==='flow_settings') { $k=save_flow($_POST); flash('success','Saved.'); redirect($flowUrl($k)); }
        if ($do==='save_step') { save_flow_step($fk,$_POST); flash('success','Step saved.'); redirect($flowUrl($fk)); }
        if ($do==='delete_step') { flow_delete_step($fk,trim((string)($_POST['step_key']??''))); flash('success','Step removed.'); redirect($flowUrl($fk)); }
        if ($do==='set_start') { flow_set_start($fk,trim((string)($_POST['step_key']??''))); flash('success','That is now the first step.'); redirect($flowUrl($fk)); }
        if ($do==='restore') { $k=flow_restore_version((int)($_POST['id']??0)); flash('success','That version is back.'); redirect($flowUrl($k)); }
        if ($do==='save_json') { flow_save_json($fk,(string)($_POST['json']??'')); flash('success','Flow replaced from JSON.'); redirect($flowUrl($fk)); }
        if ($do==='save_conn') { $k=save_flow_connection($_POST); flash('success','Connection "'.$k.'" saved.'); redirect('?page=ussd_flows'.($fk!==''?'&flow='.urlencode($fk):'').'#conns'); }
    }
    $flows=flow_list(); $fk=trim((string)($_GET['flow']??'')); $flow=$fk!==''?flow_get($fk):null;
    $conns=flow_connections(); $tplList=flow_templates(); $fromLog=null; $fromLogErr='';
    if ($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['do']??'')==='from_log') { try { $fromLog=flow_body_from_log((string)($_POST['log_line']??'')); } catch(Throwable $e){ $fromLogErr=$e->getMessage(); } }
    $def=$flow?$flow['def']:null; $steps=$def['steps']??[]; $edit=null; $editKey=trim((string)($_GET['step']??'')); if($flow && $editKey!=='' && isset($steps[$editKey])) $edit=$steps[$editKey];
    $health=$flow?flow_validate($def):[]; $nErr=count(array_filter($health,fn($h)=>$h['level']==='error')); $nWarn=count(array_filter($health,fn($h)=>$h['level']==='warn'));
    $versions=[]; if($flow){ $st=portal_pdo()->prepare('SELECT id,reason,created_by,created_at FROM ussd_flow_versions WHERE flow_key=? ORDER BY id DESC LIMIT 12'); $st->execute([$fk]); $versions=$st->fetchAll(); }
    $recent=[]; if($flow){ $st=portal_pdo()->prepare('SELECT * FROM ussd_flow_calls WHERE flow_key=? ORDER BY id DESC LIMIT 10'); $st->execute([$fk]); $recent=$st->fetchAll(); }
    $typeName=['choices'=>'choices','offers'=>'offers','ask'=>'ask','lookup'=>'look up','confirm'=>'confirm','call'=>'call','message'=>'message']; $typeBadge=['choices'=>'bg-primary','offers'=>'bg-warning text-dark','ask'=>'bg-info text-dark','lookup'=>'bg-secondary','confirm'=>'bg-dark','call'=>'bg-danger','message'=>'bg-success'];
    $go=function(array $s):string{ $t=$s['type']??''; $a=[]; if($t==='choices') foreach($s['options']??[] as $o) $a[]='“'.($o['label']??'').'” → '.($o['next']??'?'); elseif($t==='confirm') { $a[]='yes → '.($s['yes']??'?'); $a[]='no → '.($s['no']??'?'); } elseif($t==='call') foreach(['success'=>'success','lowbal'=>'low balance','fail'=>'other failure'] as $k=>$l) $a[]=$l.' → '.($s['outcomes'][$k]??'?'); elseif(in_array($t,['offers','ask'],true)) $a[]='then → '.($s['next']??'?'); elseif($t==='lookup') $a[]='shows the reply, 0 = back'; elseif($t==='message') $a[]='ends the session'; return implode('  ·  ',$a); };
    $stepKeys=array_keys($steps);
    layout_start('Service Flows'); ussd_subnav('ussd_flows');
    ?>
    <div class="cardx">
        <div class="d-flex flex-wrap justify-content-between align-items-center gap-2"><h3 class="mb-0"><i class="fa-solid fa-diagram-project me-2"></i>Service Flows</h3></div>
        <p class="text-muted small mt-2 mb-2">A service flow is a special menu built from a few blocks — <b>choices</b>, <b>offers</b>, <b>ask</b> (the customer types something), <b>look up</b> (read something from Hera), <b>confirm</b>, <b>call</b> (the call that changes something; its <i>outcome</i> — success, low balance or other failure — decides the next step) and <b>message</b>. Build one here, try it right on this page, then put it in a menu with the <b>Service flow</b> item type in the <a href="?page=ussd_menu">Menu Builder</a>. Every flow starts in <b>Test</b>: calls are rehearsed, nothing is sent.</p>
        <div class="d-flex flex-wrap gap-2 mb-2"><?php foreach($flows as $f0):?><a class="btn btn-sm <?=$f0['flow_key']===$fk?'btn-primary':'btn-outline-primary'?>" href="<?=e($flowUrl($f0['flow_key']))?>"><?=e($f0['title'])?> <span class="badge <?=$f0['mode']==='live'?'bg-danger':'bg-secondary'?>"><?=e($f0['mode'])?></span><?=$f0['status']==='inactive'?' (off)':''?></a><?php endforeach;?><?php if(!$flows):?><span class="text-muted small">No flows yet.</span><?php endif;?></div>
        <details <?=$flows?'':'open'?>><summary class="small">New flow</summary>
            <form method="post" class="row g-2 mt-1"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="do" value="new_flow">
                <div class="col-md-3"><input class="form-control" name="flow_key" placeholder="key, e.g. loan_offer" maxlength="40"></div>
                <div class="col-md-4"><input class="form-control" name="title" placeholder="Title, e.g. Purchase with loan" maxlength="80"></div>
                <div class="col-md-4"><select class="form-select" name="template"><option value="">Empty — I will add the steps</option><?php foreach($tplList as $tk=>$tp):?><option value="<?=e($tk)?>">Start from: <?=e($tp['title'])?></option><?php endforeach;?></select></div>
                <div class="col-md-1"><button class="btn btn-primary w-100">Create</button></div></form></details>
    </div>
    <?php if($flow):?>
    <div class="row g-3 mt-1">
        <div class="col-lg-7">
            <div class="cardx"><div class="d-flex justify-content-between align-items-center"><h3 class="mb-2">Check — <?=e($flow['title'])?></h3><span><?php if($nErr):?><span class="badge bg-danger"><?=$nErr?> to fix</span><?php elseif($nWarn):?><span class="badge bg-warning text-dark"><?=$nWarn?> to look at</span><?php else:?><span class="badge bg-success">all good</span><?php endif;?></span></div>
                <?php if(!$health):?><p class="small text-muted mb-0">Every step leads somewhere and every call is set up.</p><?php else:?><ul class="list-unstyled small mb-0"><?php foreach($health as $h):?><li class="py-1"><span class="badge <?=['error'=>'bg-danger','warn'=>'bg-warning text-dark','info'=>'bg-info text-dark'][$h['level']]?> me-1"><?=['error'=>'fix','warn'=>'check','info'=>'note'][$h['level']]?></span><?=e($h['msg'])?></li><?php endforeach;?></ul><?php endif;?></div>
            <?php $usedIn=flow_usage($fk);?>
            <div class="cardx mt-3"><h3 class="mb-2">Where it is used</h3>
                <?php if(!$usedIn):?><p class="small text-muted mb-0">Not in any menu yet — customers cannot reach it. In the <a href="?page=ussd_menu">Menu Builder</a> add an item of type <b>Service flow</b> and choose “<?=e($flow['title'])?>”.</p>
                <?php else:?><ul class="small mb-0"><?php foreach($usedIn as $u):?><li><a href="?page=ussd_menu&short_code=<?=urlencode($u['short_code'])?>"><?=e($u['short_code'])?></a> — “<?=e($u['label'])?>” <?=$u['status']==='active'?'<span class="badge bg-success">on</span>':'<span class="badge bg-secondary">'.e($u['status']).'</span>'?></li><?php endforeach;?></ul><?php endif;?></div>
            <div class="cardx mt-3"><h3>Steps</h3>
                <?php foreach($steps as $sk=>$s0): $isStart=($def['start']??'')===$sk;?>
                <div class="border rounded p-2 mb-2 <?=$isStart?'border-primary':''?>">
                    <div class="d-flex flex-wrap align-items-center gap-2"><code><?=e($sk)?></code><span class="badge <?=$typeBadge[$s0['type']]??'bg-secondary'?>"><?=e($typeName[$s0['type']]??$s0['type'])?></span><?php if($isStart):?><span class="badge bg-primary">first step</span><?php endif;?>
                        <span class="ms-auto text-nowrap"><a class="btn btn-sm btn-light border py-0 px-1" title="Edit" href="<?=e($flowUrl($fk,'&step='.urlencode($sk)))?>#stepform"><i class="fa-solid fa-pen"></i></a>
                        <?php if(!$isStart):?><form method="post" class="d-inline"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="do" value="set_start"><input type="hidden" name="flow_key" value="<?=e($fk)?>"><input type="hidden" name="step_key" value="<?=e($sk)?>"><button class="btn btn-sm btn-light border py-0 px-1" title="Make this the first step"><i class="fa-solid fa-flag"></i></button></form>
                        <form method="post" class="d-inline" data-confirm="Remove the step <?=e($sk)?>? Steps that lead to it will point nowhere."><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="do" value="delete_step"><input type="hidden" name="flow_key" value="<?=e($fk)?>"><input type="hidden" name="step_key" value="<?=e($sk)?>"><button class="btn btn-sm btn-light border py-0 px-1 text-danger" title="Remove"><i class="fa-solid fa-trash"></i></button></form><?php endif;?></span></div>
                    <?php if(!empty($s0['text'])):?><div class="small mt-1" style="white-space:pre-wrap"><?=e($s0['text'])?></div><?php endif;?>
                    <?php if($s0['type']==='offers'):?><div class="small text-muted">offers of: <?=e(implode('; ',(array)($s0['sub_categories']??[])))?></div><?php endif;?>
                    <?php if(in_array($s0['type'],['call','lookup'],true)):?><div class="small text-muted"><?=e(($s0['connection']??'')?:'(no connection yet)')?> / <?=e(($s0['path']??'')?:'(no path yet)')?></div><?php endif;?>
                    <div class="small text-muted"><?=e($go($s0))?></div></div>
                <?php endforeach;?>
            </div>
            <div class="cardx mt-3" id="stepform"><h3><?=$edit?'Change step “'.e($editKey).'”':'Add a step'?></h3>
                <datalist id="stepKeys"><?php foreach($stepKeys as $k0):?><option value="<?=e($k0)?>"><?php endforeach;?><option value="@exit"></datalist>
                <form method="post" class="stepform row g-2"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="do" value="save_step"><input type="hidden" name="flow_key" value="<?=e($fk)?>">
                    <div class="col-md-4"><label class="small text-muted mb-0">Step name <small>(letters, digits, _)</small></label><input class="form-control" name="step_key" value="<?=e($edit?$editKey:'')?>" <?=$edit?'readonly':''?> placeholder="e.g. confirm_buy" maxlength="30"></div>
                    <div class="col-md-8"><label class="small text-muted mb-0">What does this step do?</label><select class="form-select" name="type" id="step_type"><?php foreach(['choices'=>'Show choices (a list of options)','offers'=>'Show offers from the catalogue','ask'=>'Ask the customer to type something','lookup'=>'Look something up and show it','confirm'=>'Ask to confirm (yes / no)','call'=>'Make a call (changes something) — then branch on the result','message'=>'Show a message and end'] as $v=>$la):?><option value="<?=e($v)?>" <?=($edit['type']??'choices')===$v?'selected':''?>><?=e($la)?></option><?php endforeach;?></select></div>
                    <div class="fld t-choices t-offers t-ask t-lookup t-confirm t-message col-12"><label class="small text-muted mb-0">Screen text <small>(you can use {offer.name} {offer.price_d} {other_local} {result.…} {reply_text} …)</small></label><textarea class="form-control" rows="2" name="text" maxlength="400"><?=e($edit['text']??'')?></textarea></div>
                    <div class="fld t-choices col-12"><label class="small text-muted mb-0">Options — one per line: <code>Label -&gt; step_name</code> (<code>@exit</code> leaves the flow)</label><textarea class="form-control code" rows="3" name="options" placeholder="Purchase offer -&gt; pick&#10;Check balance -&gt; balance"><?php foreach(($edit['options']??[]) as $o0) echo e(($o0['label']??'').' -> '.($o0['next']??''))."\n";?></textarea></div>
                    <div class="fld t-offers col-md-8"><label class="small text-muted mb-0">Sub-categories <small>(one per line or separated by ;)</small></label><textarea class="form-control" rows="2" name="sub_categories"><?=e(implode("\n",(array)($edit['sub_categories']??[])))?></textarea></div>
                    <div class="fld t-offers col-md-4"><div class="form-check mt-4"><input class="form-check-input" type="checkbox" name="auto_single" value="1" id="as" <?=(!$edit||($edit['auto_single']??true))?'checked':''?>><label class="form-check-label small" for="as">If only one offer, choose it for the customer</label></div></div>
                    <div class="fld t-ask col-md-4"><label class="small text-muted mb-0">Expecting</label><select class="form-select" name="kind"><?php foreach(['phone'=>'a phone number','digits'=>'digits only','text'=>'a short text'] as $v=>$la):?><option value="<?=e($v)?>" <?=($edit['kind']??'phone')===$v?'selected':''?>><?=e($la)?></option><?php endforeach;?></select></div>
                    <div class="fld t-ask col-md-4"><label class="small text-muted mb-0">Keep it as <small>({name}, {name_local}, {name_raw})</small></label><input class="form-control" name="var" value="<?=e($edit['var']??'other')?>" maxlength="21"></div>
                    <div class="fld t-offers t-ask col-md-4"><label class="small text-muted mb-0">Then go to</label><input class="form-control" name="next" list="stepKeys" value="<?=e($edit['next']??'')?>"></div>
                    <div class="fld t-confirm col-md-6"><label class="small text-muted mb-0">If they answer 1 (yes) go to</label><input class="form-control" name="yes" list="stepKeys" value="<?=e($edit['yes']??'')?>"></div>
                    <div class="fld t-confirm col-md-6"><label class="small text-muted mb-0">If they answer 0 or 2 (no) go to</label><input class="form-control" name="no" list="stepKeys" value="<?=e($edit['no']??'@exit')?>"></div>
                    <div class="fld t-lookup t-call col-md-5"><label class="small text-muted mb-0">Connection <small>(below)</small></label><select class="form-select" name="connection"><option value="">—</option><?php foreach($conns as $c0):?><option value="<?=e($c0['conn_key'])?>" <?=($edit['connection']??'')===$c0['conn_key']?'selected':''?>><?=e($c0['title'])?> (<?=e($c0['conn_key'])?>)</option><?php endforeach;?></select></div>
                    <div class="fld t-lookup t-call col-md-7"><label class="small text-muted mb-0">Path added to the connection's address</label><input class="form-control" name="path" value="<?=e($edit['path']??'')?>" placeholder="e.g. subscribe"></div>
                    <div class="fld t-lookup t-call col-12"><label class="small text-muted mb-0">Request body <small>(JSON; placeholders like {msisdn} {offer.code} {other_msisdn} {imsi} {local_address_json}. Paste a Mobius log line under “Connections” to get one.)</small></label><textarea class="form-control code" rows="4" name="body"><?=e($edit['body']??'')?></textarea></div>
                    <div class="fld t-call col-md-4"><label class="small text-muted mb-0">On success go to</label><input class="form-control" name="on_success" list="stepKeys" value="<?=e($edit['outcomes']['success']??'')?>"></div>
                    <div class="fld t-call col-md-4"><label class="small text-muted mb-0">On low balance go to</label><input class="form-control" name="on_lowbal" list="stepKeys" value="<?=e($edit['outcomes']['lowbal']??'')?>"></div>
                    <div class="fld t-call col-md-4"><label class="small text-muted mb-0">On any other failure go to</label><input class="form-control" name="on_fail" list="stepKeys" value="<?=e($edit['outcomes']['fail']??'')?>"></div>
                    <div class="col-12 d-flex gap-2 align-items-center"><button class="btn btn-primary"><?=$edit?'Save changes':'Add step'?></button><?php if($edit):?><a class="btn btn-outline-secondary" href="<?=e($flowUrl($fk))?>">Cancel</a><?php endif;?><div class="form-check ms-2"><input class="form-check-input" type="checkbox" name="make_start" value="1" id="ms"><label class="form-check-label small" for="ms">make it the first step</label></div></div>
                </form>
            </div>
        </div>
        <div class="col-lg-5">
            <div class="cardx"><h3>Settings</h3>
                <form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="do" value="flow_settings"><input type="hidden" name="flow_key" value="<?=e($fk)?>">
                    <label class="small text-muted mb-0">Title</label><input class="form-control mb-2" name="title" value="<?=e($flow['title'])?>">
                    <div class="row g-2"><div class="col-6"><label class="small text-muted mb-0">Mode</label><select class="form-select mb-2" name="mode"><option value="test" <?=$flow['mode']==='test'?'selected':''?>>Test — calls are rehearsed</option><option value="live" <?=$flow['mode']==='live'?'selected':''?>>Live — calls are real</option></select></div>
                    <div class="col-6"><label class="small text-muted mb-0">In Test, every call ends as</label><select class="form-select mb-2" name="test_outcome"><?php foreach(['success'=>'success','lowbal'=>'low balance','fail'=>'failure'] as $v=>$la):?><option value="<?=e($v)?>" <?=$flow['test_outcome']===$v?'selected':''?>><?=e($la)?></option><?php endforeach;?></select></div></div>
                    <label class="small text-muted mb-0">Status</label><select class="form-select mb-2" name="status"><option value="active" <?=$flow['status']==='active'?'selected':''?>>Active</option><option value="inactive" <?=$flow['status']==='inactive'?'selected':''?>>Off</option></select>
                    <button class="btn btn-primary w-100">Save settings</button></form>
                <p class="small text-muted mt-2 mb-0">To put it in a menu: <a href="?page=ussd_menu">Menu Builder</a> → add an item → <b>Service flow</b> → <code><?=e($fk)?></code>.</p></div>
            <?php
            $tr=array_values(array_filter(explode(',',(string)($_GET['trail']??'')),fn($x)=>$x!=='')); $rp=trim((string)($_GET['reply']??'')); if($rp!=='') $tr[]=$rp; $tr=array_slice($tr,-30);
            $tsim=(string)($_GET['fsim']??'success'); if(!in_array($tsim,['success','lowbal,success','lowbal,fail','lowbal','fail'],true)) $tsim='success';
            $tscr=flow_screen($def,$tr,['call'=>flow_sim_call_hook($tsim),'lookup'=>'flow_sim_lookup','msisdn'=>'220866000001']); $tshow=($tscr['text']??'') !== '' ? (string)$tscr['text'] : (isset($tscr['exit_at'])?'(back to the menu)':'(nothing to show)'); $tend=!empty($tscr['end'])||isset($tscr['exit_at']);
            ?>
            <div class="cardx mt-3"><h3>Try it</h3>
                <form method="get" class="mb-2"><input type="hidden" name="page" value="ussd_flows"><input type="hidden" name="flow" value="<?=e($fk)?>"><input type="hidden" name="trail" value="<?=e(implode(',',array_slice($tr,0,max(0,count($tr)-0))))?>">
                    <label class="small text-muted mb-0">If a call is made, pretend Hera says</label><select class="form-select form-select-sm" name="fsim" data-autosubmit><?php foreach(['success'=>'success','lowbal,success'=>'low balance, then success on the next call (e.g. a loan)','lowbal,fail'=>'low balance, then failure','lowbal'=>'low balance','fail'=>'failure'] as $fv=>$fl):?><option value="<?=e($fv)?>" <?=$tsim===$fv?'selected':''?>><?=e($fl)?></option><?php endforeach;?></select></form>
                <div class="ussd-phone"><div class="ussd-screen"><?=nl2br(e($tshow))?></div>
                    <?php if($tend):?><div class="alert alert-secondary py-2 mt-2 mb-2">Session ended.</div><a class="btn btn-primary" href="<?=e($flowUrl($fk,'&fsim='.urlencode($tsim)))?>">Dial again</a>
                    <?php else:?><form method="get" class="d-flex gap-2 mt-2"><input type="hidden" name="page" value="ussd_flows"><input type="hidden" name="flow" value="<?=e($fk)?>"><input type="hidden" name="trail" value="<?=e(implode(',',$tr))?>"><input type="hidden" name="fsim" value="<?=e($tsim)?>"><input class="form-control" name="reply" autocomplete="off" autofocus placeholder="Your reply"><button class="btn btn-primary">Send</button><a class="btn btn-outline-secondary" href="<?=e($flowUrl($fk,'&fsim='.urlencode($tsim)))?>">Restart</a></form><?php endif;?></div>
                <div class="small text-muted mt-2">Replies so far: <b><?=$tr?e(implode(' → ',$tr)):'(none)'?></b>. Calls and look-ups here are always simulated.</div></div>
            <?php if($recent):?><div class="cardx mt-3"><h3>Recent calls</h3><div class="table-scroll" style="max-height:240px;overflow-y:auto"><table class="table table-sm mb-0 small"><tbody><?php foreach($recent as $r0):?><tr><td class="text-nowrap"><?=e($r0['created_at'])?></td><td><?=e($r0['msisdn'])?></td><td><?=e($r0['step_key'])?></td><td><span class="badge <?=['success'=>'bg-success','lowbal'=>'bg-warning text-dark','fail'=>'bg-danger'][$r0['outcome']??'']??'bg-secondary'?>"><?=e($r0['outcome']??'…')?></span> <span class="text-muted"><?=e($r0['mode'])?></span></td><td title="<?=e((string)$r0['response'])?>"><i class="fa-solid fa-circle-info text-muted"></i></td></tr><?php endforeach;?></tbody></table></div></div><?php endif;?>
            <div class="cardx mt-3"><h3>History</h3>
                <?php if(!$versions):?><p class="small text-muted mb-0">Every change is kept here.</p><?php else:?><div class="table-scroll" style="max-height:220px;overflow-y:auto"><table class="table table-sm mb-0 small"><tbody><?php foreach($versions as $v):?><tr><td class="text-nowrap"><?=e(date('M j H:i',strtotime($v['created_at'])))?></td><td><?=e($v['created_by']??'')?></td><td><?=e($v['reason'])?></td><td class="text-end"><form method="post" data-confirm="Bring this version back?"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="do" value="restore"><input type="hidden" name="id" value="<?=e($v['id'])?>"><button class="btn btn-sm btn-outline-secondary py-0">Restore</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
                <details class="mt-2"><summary class="small">Advanced: the whole flow as JSON</summary><form method="post" class="mt-2"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="do" value="save_json"><input type="hidden" name="flow_key" value="<?=e($fk)?>"><textarea class="form-control code mb-2" rows="8" name="json"><?=e(json_encode($def,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></textarea><button class="btn btn-outline-primary btn-sm">Replace the flow with this JSON</button></form></details></div>
        </div>
    </div>
    <?php endif;?>
    <div class="cardx mt-3" id="conns"><h3>Connections <small class="text-muted">— where a call goes</small></h3>
        <p class="small text-muted">A connection is an address plus its headers (kept encrypted, never shown again), what result code means success, and which words mean "low balance". A call step picks a connection and adds its own path.</p>
        <?php if($conns):?><table class="table table-sm small"><thead><tr><th>Key</th><th>Title</th><th>Address</th><th>Headers</th><th>Success code</th></tr></thead><tbody><?php foreach($conns as $c0):?><tr><td><code><?=e($c0['conn_key'])?></code></td><td><?=e($c0['title'])?></td><td><?=e($c0['base_url'])?></td><td><?=$c0['has_headers']?'saved':'none'?></td><td><?=e($c0['ok_code'])?></td></tr><?php endforeach;?></tbody></table><?php endif;?>
        <form method="post" class="row g-2"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="do" value="save_conn"><input type="hidden" name="flow_key" value="<?=e($fk)?>">
            <div class="col-md-3"><input class="form-control" name="conn_key" placeholder="key, e.g. hera_loans" value="<?=e((string)($_POST['conn_key']??''))?>"></div><div class="col-md-3"><input class="form-control" name="title" placeholder="Title"></div>
            <div class="col-md-6"><input class="form-control" name="base_url" placeholder="Address, e.g. https://vas-testing.comium.gm/hera/prepaid/" value="<?=e($fromLog['address']??'')?>"></div>
            <div class="col-md-6"><textarea class="form-control code" rows="2" name="headers" placeholder="Headers, one per line:  X-USERNAME: USSD  (leave empty to keep the saved ones)"></textarea></div>
            <div class="col-md-2"><input class="form-control" name="ok_code" value="0" title="Result code that means success"></div><div class="col-md-2"><input class="form-control" name="timeout" value="8" title="Timeout in seconds"></div>
            <div class="col-md-12"><input class="form-control" name="lowbal" value="insufficient,low balance,not enough" title="Words that mean low balance"></div>
            <div class="col-12"><button class="btn btn-outline-primary btn-sm">Save connection</button> <small class="text-muted">saving a key that exists updates it</small></div></form>
        <hr>
        <h3 class="fs-6">Get a request body from a Mobius log line</h3>
        <form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="do" value="from_log"><input type="hidden" name="flow_key" value="<?=e($fk)?>">
            <textarea class="form-control code mb-2" rows="3" name="log_line" placeholder="Paste a line like:  … Sending request :{&quot;callID&quot;:… to application:https://…  (the keys in it are ignored)"><?=e((string)($_POST['log_line']??''))?></textarea><button class="btn btn-outline-secondary btn-sm">Make the body</button></form>
        <?php if($fromLogErr):?><div class="alert alert-warning py-2 mt-2 small mb-0"><?=e($fromLogErr)?></div><?php endif;?>
        <?php if($fromLog):?><div class="mt-2 small"><div><b>Address</b>: <code><?=e($fromLog['address'])?></code> · <b>path</b>: <code><?=e($fromLog['path'])?></code> (the address is pre-filled in the form above)</div><div class="mt-1"><b>Request body</b> — copy into a call or look-up step:</div><pre class="mb-1" style="white-space:pre-wrap"><?=e($fromLog['body'])?></pre><?php foreach($fromLog['notes'] as $n0):?><div class="text-muted">• <?=e($n0)?></div><?php endforeach;?></div><?php endif;?>
    </div>
    <?php layout_end(); exit;
